name: Create Initial Gists

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  create_gists:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq and curl
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl
          which jq
          jq --version
          which curl
          curl --version

      - name: Create Gists for each file
        env:
          PAT_GITHUB_GIST: ${{ secrets.PAT_GITHUB_GIST }}  # Ensure this secret name matches
        run: |
          for file in $(git ls-files); do
            echo "Processing file: $file"
            gist_data=$(jq -n \
              --arg filename "$file" \
              --arg content "$(cat $file)" \
              '{ "files": {($filename): {"content": $content}}, "public": true }')

            echo "Payload for $file:"
            echo "$gist_data"

            curl -X POST \
              -H "Authorization: token $PAT_GITHUB_GIST" \  # Using token authorization
              -H "Accept: application/vnd.github+json" \    # Recommended API header
              -H "X-GitHub-Api-Version: 2022-11-28" \       # Recommended API version header
              -H "Content-Type: application/json" \
              -d "$gist_data" \
              https://api.github.com/gists

            echo "Created Gist for $file"
          done
