name: Create Initial Gists

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  create_gists:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq and curl
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl
          chmod +x /usr/bin/jq /usr/bin/curl
          which jq
          jq --version
          curl --version

      - name: Create Gists for each file
        env:
          FINEGRAINED_GIST_TOKEN: ${{ secrets.FINEGRAINED_GIST_TOKEN }}  # Use the fine-grained token
        run: |
          for file in $(git ls-files); do
            echo "Processing file: $file"
            gist_data=$(jq -n \
              --arg filename "$file" \
              --arg content "$(cat $file)" \
              '{ "files": {($filename): {"content": $content}}, "public": true }')

            echo "Payload for $file:"
            echo "$gist_data"

            curl -X POST \
              -H "Authorization: Bearer $FINEGRAINED_GIST_TOKEN" \  # Use the Bearer token for auth
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -d "$gist_data" \
              https://api.github.com/gists

            echo "Created Gist for $file"
          done
