name: Add or Update Files in Gist

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  add_or_update_files_in_gist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq and curl
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl
          which jq
          jq --version
          which curl
          curl --version

      - name: Add or update files in the specific Gist
        env:
          PAT_GITHUB_GIST: ${{ secrets.PAT_GITHUB_GIST }}  # Ensure this secret name matches
        run: |
          GIST_ID="7a2e16cf9a0c5d13aedc40cf7f2a764b"  # Your specific Gist ID
          
          for file in $(git ls-files); do
            echo "Processing file: $file"
            gist_data=$(jq -n \
              --arg filename "$file" \
              --arg content "$(cat $file)" \
              '{ "files": {($filename): {"content": $content}}}')

            echo "Payload for $file:"
            echo "$gist_data"

            response=$(curl -s -o /dev/null -w "%{http_code}" -X PATCH \
              -H "Authorization: token $PAT_GITHUB_GIST" \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -H "Content-Type: application/json" \
              -d "$gist_data" \
              https://api.github.com/gists/$GIST_ID)

            if [ "$response" -eq 200 ]; then
              echo "Successfully added or updated file $file in Gist $GIST_ID"
            else
              echo "Failed to update Gist $GIST_ID with file $file, response code: $response"
            fi
          done
